### ISSUE TITLE
[Not] compatible with the current version of JupyterLab.

### ISSUE THREAD

**Issue by abngal** [jupyterlab/jupyterlab-google-drive#171]
I am using jupyter using docker-compose:  

_docker-compose.yml_
```
version: '3'

services:
    jupyter:
        image: jupyter/tensorflow-notebook:15a66513da30 # 2020-03-17
        ports:
        - 10000:8888
        volumes:
        - ./jupyter:/home/jovyan/work
        environment:
        - JUPYTER_ENABLE_LAB=yes
```

I tried to install using jupyterlab extension manager (on the web-based gui).

```
Extension Installation Error
An error occurred installing @jupyterlab/google-drive.

Error message:

No version of @jupyterlab/google-drive could be found that is compatible with the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.2 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.0.2 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/apputils
>=4.0.2 <4.1.0          >=3.0.0 <4.0.0 @jupyterlab/coreutils
>=2.0.2 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/docmanager
>=2.0.2 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/filebrowser
>=5.0.2 <5.1.0          >=4.0.0 <5.0.0 @jupyterlab/services

```

[image](https://user-images.githubusercontent.com/33404820/76892592-e818b200-68c5-11ea-8eca-dc01cf930284.png)

( Seems the "similar" issues are about old compatability errors for earlier versions. )
