### ISSUE TITLE
No sign in button visible and no errors in console - Z2JH -  solved

### ISSUE THREAD

**Issue by dwilliams782** [jupyterlab/jupyterlab-google-drive#177]
Hi all,

I thought I'd share the answer to a problem I found recently. 

We have Jupyterhub installed via the Z2JH project, with the Oauthenticator configured to provide Google log in.

With the drive extension installed, we weren't presented with a login or scope acceptance page on the Drive extension, instead we got a blank tab with a number of 403s in the panel.

It took me a while to figure out what was happening. We had different Client IDs associated with the Google login page and the Drive extension, but ultimately these were from the same project which meant the same Oauth Consent screen. This means they are both the same "app" in Google's eyes.

When you log in with Google to JH, it only requests auth.info and auth.email scopes, so you need to override the default scopes in the Helm chart for Z2JH to prompt for the Drive scope upon login:

```
  auth:
    type: google
    google:
      callbackUrl: "<your-url>/hub/oauth_callback"
    scopes:
      - "openid"
      - "email"
      - "https://www.googleapis.com/auth/drive"
```

This way your users will only see one log in button initially, and won't be prompted again by the Drive extension. 

Another option is to use a client ID associated with a different Oauth Consent screen, but this requires two GCP projects and inevitably two sign in buttons.

This may seem obvious now but it took me a while to figure out and I didn't see anyone report an answer here so I thought I'd share.
